server:
  port: 8080


spring:
  application:
    name: interview
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/interview?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    druid:
      username: root
      password: 12345678
      url: jdbc:mysql://localhost:3306/interview?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 8
      max-active: 16
      min-idle: 1
      max-wait: 60000

  redis:
    database: 1
    host: localhost
    port: 6379
    password: 123456
    timeout: 5000

  mybatis-plus:
    type-aliases-package: com.cxh.interview.entity
    mapper-locations: classpath:mapper/*.xml,classpath:mapper/**/*.xml
    configuration:
      jdbc-type-for-null: null
      cache-enabled: false
    global-config:
      banner: false